### ISSUE TITLE
Running Pysolotools-fiftyone Exception: Found none or multiple metadata files

### ISSUE THREAD

**Issue by gatordevin** [Unity-Technologies/pysolotools-fiftyone#14]
Hi. I am attempting to run the pysolotools-fiftyone version 0.3.25 and running into an issue when trying to open an example dataset using the following command.

`pysolotools-fiftyone examples/groceries`

Here is the full error trace. It was able to launch fiftyone in my browser, but after this, the program failed.

`Migrating database to v0.18.0
App launched. Point your web browser to http://localhost:5151
Traceback (most recent call last):
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\Scripts\pysolotools-fiftyone.exe\__main__.py", line 7, in <module>
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 588, in cli
    main(sys.argv[1:])
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 584, in main
    session.start()
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 565, in start
    self._start_internal()
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 561, in _start_internal
    importer = SoloDatasetImporter(self._solo, max_samples=5)
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 74, in __init__
    self._solo = Solo(dataset_dir)
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools\consumers\solo.py", line 58, in __init__
    self.metadata = self.__open_metadata__(metadata_file)
  File "C:\Users\gator\anaconda3\envs\unitysyntheticdata\lib\site-packages\pysolotools\consumers\solo.py", line 138, in __open_metadata__
    raise Exception("Found none or multiple metadata files.")
Exception: Found none or multiple metadata files.`

**Comment by StevenBorkman** [comment]
I'm thinking that the most likely reason that you are seeing this is that the path to the dataset does not exist at the location that you are running at. The "examples/groceries" is a relative path. If you installed pysolotools from pip, then you will have to clone this repo to get the sample datasets.

Hopefully this is the issue, and not something bigger. Let me know if this fixed your issue for you.

**Comment by gatordevin** [comment]
That worked thank you for the help cant wait to use this tool.

**Comment by mshooter** [comment]
I have the same problem. 
I can't seem to use it on my own dataset. 
the error says that the img_path is expected to be a str or os.PathLike object. 
However, when I debug further it seems that the "curr.captures" variable is empty. 
Do I need to activate a certain annotation? 
My current active annotations are the following: 
`{'unity.solo.KeypointAnnotation': True, 'unity.solo.BoundingBox2DAnnotation': True, 'unity.solo.BoundingBox3DAnnotation': True, 'unity.solo.InstanceSegmentationAnnotation': False, 'unity.solo.SemanticSegmentationAnnotation': False, 'unity.solo.DepthAnnotation': True, 'unity.solo.PixelPositionAnnotation': False, 'unity.solo.NormalAnnotation': False, 'type.unity.com/unity.solo.MetadataMetric': False}`
