### ISSUE TITLE
Webpage is just blank

### ISSUE THREAD

**Issue by cs1488** [Unity-Technologies/pysolotools-fiftyone#17]
So i installed pysolotools-fiftyone in an environment created with Miniconda in Anaconda Prompt.
I am using Windows 10
I installed the pre-commit inside the env
I installed the openEXR package recommended in the tutorial from inside the env 
``pip install OpenEXR-1.3.8-cp38-cp38-win_amd64.whl```
I installed pysolotools-fiftyone

I first ran into some multiple meta errors, but for some datasets it "worked"`
I used: ``(pysolotools_env) C:\Users\chris\Downloads>pysolotools-fiftyone C:\Users\chris\AppData\LocalLow\DefaultCompany\PerceptionTutorial\solo_25``

Which got me:
``App launched. Point your web browser to http://localhost:5151
{'unity.solo.KeypointAnnotation': False, 'unity.solo.BoundingBox2DAnnotation': True, 'unity.solo.BoundingBox3DAnnotation': False, 'unity.solo.InstanceSegmentationAnnotation': False, 'unity.solo.SemanticSegmentationAnnotation': True, 'unity.solo.DepthAnnotation': True, 'unity.solo.PixelPositionAnnotation': False, 'unity.solo.NormalAnnotation': False, 'type.unity.com/unity.solo.MetadataMetric': False}
 100 [1.1m elapsed, ? remaining, 1.5 samples/s]``

Then the browser opens the page, but it is just blank.

When i CTRL+C i get:
``Traceback (most recent call last):
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\.conda\envs\pysolotools_env\Scripts\pysolotools-fiftyone.exe\__main__.py", line 7, in <module>
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 588, in cli
    main(sys.argv[1:])
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 584, in main
    session.start()
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\site-packages\pysolotools_fiftyone\solo_fiftyone.py", line 566, in start
    self._session.wait()
  File "C:\Users\chris\.conda\envs\pysolotools_env\lib\site-packages\fiftyone\core\session\session.py", line 949, in wait
    time.sleep(wait)
KeyboardInterrupt``

So then i tried downloaded the groceries example and placed it in the current directory.
Same issue except that it found the stored/cached images in the fiftyone_images directory

Any clues on what i did wrong?

**Comment by gooooodfish** [comment]
Happened to me too!!!!

**Comment by gooooodfish** [comment]
Hi, I had the same issue. I am now able to solve it. Note that I am using Mac OS with arm64 CPU. I am not sure if this will impact the result or not.

Please uninstall fiftyone in your python package and install fiftyone version 0.17.2, which is the version about at the same time when this package is developed. I was guessing the version of fiftyone is the issue and it worked!
`pip uninstall fiftyone`
`pip install fiftyone==0.17.2`
If this gives you other error about log file "error 14", please delete the log folder.

For me the new error is
`{"t":{"$date":"2023-02-10T01:18:41.220Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/Users/$username/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/Users/$username/.fiftyone/var/lib/mongo/log/mongo.log.2023-02-10T01-18-41"}}
Subprocess ['/Users/$username/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/Users/$username/.fiftyone/var/lib/mongo', '--logpath', '/Users/$username/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 14` 

I was able to solve it by
`sudo rm -r /Users/$username/.fiftyone/var/lib/mongo `

For the developer of this package, please update the requirements of this package in terms of the version of fiftyone to avoid further confusion for others to use this package.

Hope that helps!

**Comment by nroadley** [comment]
@cs1488 & @gooooodfish I had a similar issue and error message as above. From an other post I learned that if there is 1 sequence in the SOLO data that is unlabeled it will crash the SOLO to COCO converter. So I fixed that, and then tried the fiftyone visualizer again, which also then worked.

So if you like me have 1 sequence out of many that failed to have a label, then I'd recommend you to try to clean that up by replacing that sequence and trying again.
