### ISSUE TITLE
Linux install not working

### ISSUE THREAD

**Issue by lesreaper** [Unity-Technologies/pysolotools-fiftyone#18]
Ubuntu 22.04

Downloaded main repo
Running in virtual env
Installed  `pre-commit`
Installed `openexr`
Installed `pysolotools-fiftyone`

Error:
```
Subprocess ['~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/db/bin/mongod', '--dbpath', '~/.fiftyone/var/lib/mongo', '--logpath', '~/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "~/.virtualenvs/unity/bin/pysolotools-fiftyone", line 5, in <module>
    from pysolotools_fiftyone.solo_fiftyone import cli
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/pysolotools_fiftyone/solo_fiftyone.py", line 8, in <module>
    import fiftyone
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/core/odm/database.py", line 156, in establish_db_conn
    port = _db_service.port
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "~/.virtualenvs/unity/lib/python3.10/site-packages/fiftyone/core/service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```
OpenSSL (which is the libssl error) is at version 3, so not sure why the system wants `libcrypto.so.1.1`.

Also, tried to install this on a mac, and nothign but problems getting OpenEXR installed.

Any ideas about how to fix this, or maybe put this as a Docker setup?

**Comment by lesreaper** [comment]
I identified the main issue. 

Ubuntu 22.04 upgraded to OpenSSL 3.0. 

I have an old machine here running Ubuntu 18.04 where OpenSSL version 1 is the primary version. I installed `pysolotools-fiftyone`. Works great. `pysolotools-fiftyone` doesn't support past Ubuntu 18.04 at the moment.
